steps:
# Build the image
- name: "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/gcpdevops","."]
# Push the image to artifact registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push","gcr.io/$PROJECT_ID/gcpdevops"]
# Deploy to GKE cluster
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-devops-project
  - --namespace=gke-devops-prod