---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deploy-deployment
spec:
  selector:
    matchLabels:
      app: gke-deploy
  template:
    metadata:
      labels:
        app: gke-deploy
    spec:
      containers:
      - name: python-gke-deploy
        image: gcr.io/njkndubkbkjnkdjnf/gcpdevops:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gke-deploy-service
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  selector:
    app: gke-deploy
  type: "LoadBalancer"
  ports:
  - port: 80
    targetPort: 5000
    protocol: "TCP"
